language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

script:
  - pip install .
  - pip install coverage
  - pip install codecov
  - python setup.py test
  - coverage run setup.py test
  - codecov
