language: python

python:
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

script:
  - pip3 install .
  - pip3 install coverage
  - pip3 install codecov
  - python3 setup.py test
  - python3 -m coverage run -m unittest discover .
  - codecov
