language: python

python:
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

script:
  - pip install .
  - pip install coverage
  - pip install codecov
  - python setup.py test && coverage run -m unittest discover .
  - codecov
