language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

script:
  - pip install coverage
  - pip install codecov
  - python -m unittest discover .
  - coverage run -m unittest discover .
  - codecov
